### PR TITLE
Added functionality to support GPIO DAC and control power of media system

### PR DESCRIPTION
**Pull request by virtualas10**
Hello,
Great project however I faced some issues which I tried to fix and committed so project would be more universal. I have RaspberryPi 2 with PHAT DAC which give way better sound quality than integrated sound card. Pull request will cover:
-  PHAT DAC does not support ALSA volume control whilst I had to make it flexible by adding None value handler. If I am not wrong this will be common across most of DAC's and Amplifiers that connect via GPIO 
-  For security reasons BT-Speaker should now allow to set discovery to false after you paired all devices you want. Basically for setup you can use default functionality (discovery on after someone disconnect) but once paired with devices discovery mode should be off as it would allow to connect others you don't want to
-  Some TV's will not recognise BT-Speaker as it will filter out it by class. Added a bit of manual to README how to overcome it. Would be nice late to collaborate to BT-Manager and to implement Class parameter change
-  Importantly added functionality to support house automation solutions. Specifically choose Sonoff device which is easy to control via http post requests after flashing ESP Easy firmware but this can be adopted to any other. Important function over here is timeout handling. Although connect and disconnect commands are great they will not handle the application workflow which can turn into uncontrolled turn off and on of your media system. It will not allow user to add a timeout value after which if no one is connected to BT-Speaker it will turn off the media system and turn it on again if someone connects.

### CODE REVIEW

**Comment by lukasjapan** [comment]
Will arrange this pull request and merge within February.

My thoughts so far:

1)
An option to disable volume control is a good idea.
I'd rather add an `enabled = yes/no` switch as it seems more intuitive.

2)
An option for disabling discoverability is also great.
But I think the speaker should be discoverable by default for plug and play reasons.

3)
Agreed with the class.

4)
I'll refractor some parts and default settings to make the hook system a little bit more clear.
By changing the ini file, any script should can be executed on connect/disconnect.
Controlling third party technology (= stuff not directly related with speaker functionality) should be placed inside such scripts, in my opinion.

So I am thinking of putting default scripts into `/etc/bt-speaker` that are called on connect/disconnect.
Then we can add the commonly used commands/hooks inside there, commented out by default.

**Comment by djh816** [comment]
Agree with luka, would love this as an option but since I don't need, would prefer no alterations to the existing defaults that I get with the original. Great work adding functionality though :D

**Comment by lukasjapan** [comment]
partly arrange and merged in #37 except sono fixes.

should be shifted into connect/disconnect scripts (commented out by default) if possible

pullrequests regarding such things are welcome

**Comment by virtualas10** [comment]
I missed this conversation completely! The reason I hooked into the code for #4 was because I didn't wanted bt-speaker to turn off power immediately someone disconnect from BT. Implementing that within scripts require to run them as another daemons or have a timeout functionality within controller itself. Would you agree to improvement to run script or call http with timeout value instead?

**Pull request closed without merging**
