### PR TITLE
Restart aplay on IOError. Fixes #30

### LINKED ISSUE #30: Sometimes IOErrors when piping to aplay
Sometimes it happens that despite successfully connecting no sound is playing. Looking at the logs I see:

```
Traceback (most recent call last):
Jan 26 11:21:02 raspberrypi bt_speaker.py[1859]:   File "/usr/lib/python2.7/dist-packages/gi/override
Jan 26 11:21:02 raspberrypi bt_speaker.py[1859]:     func_fdtransform = lambda _, cond, *data: callba
Jan 26 11:21:02 raspberrypi bt_speaker.py[1859]:   File "/opt/bt-speaker/bt_manager/audio.py", line 1
Jan 26 11:21:02 raspberrypi bt_speaker.py[1859]:     self.user_cb(self.user_arg)
Jan 26 11:21:02 raspberrypi bt_speaker.py[1859]:   File "/opt/bt-speaker/bt_manager/audio.py", line 5
Jan 26 11:21:02 raspberrypi bt_speaker.py[1859]:     self.raw_audio(self.read_transport())
Jan 26 11:21:02 raspberrypi bt_speaker.py[1859]:   File "/opt/bt-speaker/bt_speaker.py", line 64, in 
Jan 26 11:21:02 raspberrypi bt_speaker.py[1859]:     # pipe to the play command
Jan 26 11:21:02 raspberrypi bt_speaker.py[1859]: IOError: [Errno 32] Broken pipe
```
Reconnecting does not help.
Restarting bt_speaker fixes this.
This seems to be happening mostly over night. At evening before everything works great and the next morning it doesn't. But it doesn't happen every night.

I don't no what exactly is causing the IOError, but I think it would be good to handle it gracefully.
For me just doing sys.exit(1) on such an error would be enough, as systemd will immediately restart the service and everything will be working again.

I am running bt-speaker on a Raspberry Pi 1B. 
(I know this is not the officially supported Hardware, but it is working really great. Much better than the pulseaudio solution I tried before.)

### PR DESCRIPTION
**Pull request by dbaumgarten**
This PR fixes the IOErrors occuring when the aplay process crashes, what happens somewhat often on the RPi 1b. 
See Issue #30

### CODE REVIEW

**Comment by djh816** [comment]
hey dbaumgarten, have you tried the audio pipe fix in the other forks? I had a really hacky try and catch when mine would have disconnects but it wasn't good for much other than kicking the pi back into discovery mode. Since applying the audio pipe fix, I have not had any issues at all, but maybe this would still be a good failsafe case to have

**Comment by djh816** [comment]
one thing for example that always disconnected on mine, voice typing on android

**Comment by dbaumgarten** [comment]
The Pipe-Error fix in #36 seems to do exactly the same thing as this one.

When #36 gets merged this PR can be closed.

**Comment by lukasjapan** [comment]
arranged and merged in #37

**Pull request closed without merging**
